language: python
sudo: required
dist: xenial
python:
- '3.7'
- pypy3.5-6.0
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: SvsiYc4uFI2zdjRpNDEd8mYv7uYuMnb3mA3VMKet/5xGOkIyMzB1snXSXVaMmWTYWBX1z4wlMkx72nXt/pLTAbui3x/u4cx5IzZmy2juc2q9YTkERRmOhZ7LsaBwfQ6OBYRwXWwUm9TLkHSZ6Y5RBWF4dU5tb+qw1V8yfR7aj8TPVzNjcS2PaSdmkKPjLpyftEdk9kwYGAiUd5NXMCjgV701PYVG7W2x5Lwunm2nfovGElkB6IPyik8KBS7VhvhipffDkR2uiLEGl6o3dqFnaXK0DD9cSKRICFwYGbkCeduqEbpmu/BHkf00nsgJ4uK12+n2lcFdgzBQHaXhjlxdRqAaVPkqPucgOENEuL9KBNP/1jf21qkiq8AfNbgac+h0kjYptEPED5mKPA+OmxViq4bVI+tbFh2Mf4yY4O/zIhP078inPptsWqCpAFSy7YrgK/oi28TXUrFI6jHQW22X6cnGLSv4xJsYHzadKqqJDk/w9bRfFv9ebsZXppstpwXQcnLny2DFKize8oNkA3vQwjN97GCS4kRStzUrUOwiuKLpbk+1qTMP1qRFlj8UbfUHHnjkIoHXgctOH4zNCZhaRQkGhLZQdca4ffSB29n0SH68h9GBttOlLBqoVevwWXktpjam+cTY8UQo1/cNuT/YORwwQYTWGXG3Waa//cVmMeo=
  on:
    branch: master
