language: python
sudo: required
dist: xenial
python:
- '3.7'
- pypy3.5-6.0
install:
- pip install tox-travis
- pip install coveralls
script:
- tox
- coveralls
deploy:
  provider: pypi
  user: cmaclell
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: TWVpcuVJ2k3/nvJ+gtg2WYKKS5McGxYe4hZCNbOt6VgdJFmhoZv7fg8F726/xI5TDv8NvACYE/L+raF0+1QMyKP4KZq1auV959XUe+k3DOJjgunq3BPYwznqvTGo+CDOiAhDQ0yksjDE2IaMQPyVTKN/d3j5+1RPGkoynocJbDSMCbTqZhnjnL4ryj/GWOJqJ/m//GKgZoKV23hldL0fc+RHJayJProXf38u52ufJIQqq5XtibE90Ctj6yNQkxEk1UBI+wTn8pflnCUFsrY/ksWMdONVjvS2vPwToHLHgKQMt7yRi7lPg08hCTcSagQZZVTE8I+mAg3aY5Z18emsRB7F7W4yeqySDwP0L8DDLvQ0MywITARLf+XAhHZk917YmKidqebOLmjadgU8Kot/nI9bdv85Ps/abYTaydL5HxxCcEOLM1GHn2cRBHDJRWcTuejcQPrMkOYj1eSOyn77U3pj5gwtPYmN81Q3OVhn6eGuEJ7MiOFAQdNye6XYnehGoIaveD+oeBxt/6AXCitcUPgIgTcPhYLPDSb0KsXOmHZkmhQ5kN2qzlBxTymSdiGc1DCdxnmNvXusokQRUEN/PG6H+z2NayKCXBdx9OmCDiAkSQqIYHTHatFsrxA3015iJCswtlP5UpGJBEOWbJaejhbw83Tw1mD7xM345lUFvAc=
  on:
    branch: master
